### ISSUE TITLE
As editors we want to create an additional banner option to communicate certain messages to meet our brand positioning strategy

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1886] opened 2023-09-15 12:14 UTC
New banner designs 1. Create a new banner based on DEFAULT banner. **Default + Big text**
1. Additional rich text component to be placed between the TITLE (H1) and the image.
2. Rich text element should feature two text sizes. Large and extra large. Use all options in current rich text element (bold / Subscript etc)
3. Add colour option choice in rich text element to allow editors to highlight key words. Use Energy red #.
3. The sketch for desktop should indicate a rough size but please loop Nick in once set up to finalise the pixel sizes and spacing.
4. Consider how to name the two font sizes in terms of H numbers. 
5. Banner should be available on TOPIC and MAGAZINE templates.
6. Banner should be available on ALL SITES
7. Consider if banner can be placed under specific user group to limit usage.
8. Text should follow accessibility as per rich text component.

Sketches available on CMS Figma board on BIG TEXT page.

**Comment by NickHaggerty1** [comment] 2023-09-15 12:14
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnVrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--31dcf473a4f0abdad01c2f02d5a8a7ebbed4361a/default%20%2B%20big%20text%20banner-1.png)

**Comment by fernandolucchesi** [comment] 2023-11-02 07:38
Duplicate of #1887

**Closed by fernandolucchesi** 2023-11-02 07:38 UTC
Labels: 📇 user story
