### ISSUE TITLE
Investigate/add twitter feed to the german site

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1095] opened 2022-05-19 06:52 UTC

**Comment by padms** [comment] 2022-06-07 15:30
Initial component is ready for review.

**Comment by wenche** [comment] 2022-06-08 08:11
**Some comments**
- We should consider to add a title, an ingress and the option to choose a background colour since that's how the majority of the rest of the components work. If the publisher want a title then this setup will contribute to spacing issues. We already have an issue to fix this for [the cookie consent component.](https://github.com/equinor/energyvision/issues/1009) What do you think @BirteThornquist @meols 
- It would be nice if we could validate the input for  the embed value field in Sanity. There's nothing that restricts you from doing this
![Skjermbilde 2022-06-08 kl. 09.55.01.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8000e1bd-7969-4eae-b9bb-238f8565e1d6the)
And the result in the web is an error in the console and no visible tweet. 
![Skjermbilde 2022-06-08 kl. 09.56.52.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/418bfd64-a5a6-4d1f-85d0-7ca39c6a324f)
I would suggest to look into to improve this by checking if the string consists of numbers if it is a tweet. As far as I can see, that's the expected behaviour https://developer.twitter.com/en/docs/twitter-ids. And/or improve the error handling for the web.
- IMHO it's easier to read `className="cookieconsent-optin-marketing"` than `className={'cookieconsent-optin-marketing'}`
- The CSS variable` var(--iframe-innerPadding)` does not exist, and there's no way that someone from outside can  add this. Some copy'n paste gone wrong? Should be simplified

**Comment by wenche** [comment] 2022-06-08 10:43
Forgot to mention one thing: It's better to return null instead on an empty div in the switch

**Comment by fernandolucchesi** [comment] 2022-06-10 11:36
Just a nit pick, we can use the "Rule" type when writing validations in Sanity instead of any.

`import { Rule } from '@sanity/types'
`

**Comment by padms** [comment] 2022-06-14 08:21
Changed any to Rule

**Comment by fernandolucchesi** [comment] 2022-06-16 08:09
@meols, can you please test this one on https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/ ?

**Comment by padms** [comment] 2022-06-21 11:49
@meols I used equinor_de as the value.

**Comment by meols** [comment] 2022-06-22 12:29
@padms - it doesn't seem to work for me with this setting. 
- Anything I should change?
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/0e64cbe6-2781-415b-9ec1-3d22cc9872ca)
- Also I see a glimpse of a cookie message that doesn't stay (see attached mp4 file) . As I asked in my previous comment as well; does the twitter feed trigger any cookies?
- If yes, should the component have a choose cookie field as well?

https://images.zenhubusercontent.com/224120954/db635110-259a-4270-898b-794b5c36258e/twittertest.mp4

**Comment by padms** [comment] 2022-06-24 05:29
@meols : Yes, Twitter feed sets marketing cookies when user interacts with the feed. By default Cookie consent banner shows up to asking the user for requesting marketing cookies. Otherwise the feed loads correctly. 
I checked in my mobile and the feed loads properly. Could you check if there is something that is blocking twitter.

**Comment by padms** [comment] 2022-06-27 14:58
Improved help text

**Comment by meols** [comment] 2022-06-28 08:20
@padms - Great if you can add validation for the relevant fields, as suggested in the meeting.
Suggestions for improving texts:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/3fd71807-c999-4db8-b3c5-48a16aed86b7)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/4efe7668-3b76-486c-9e1d-30f10186e41b)
Enter tweetid (number) for embedding single tweet or username/handle of twitter profile for embedding timeline.

**Comment by meols** [comment] 2022-06-28 09:02
@padms - Also I think it should show somewhere in the component that it sets marketing cookies, so that editors knows this

**Closed** 2022-07-11 08:17 UTC
