### ISSUE TITLE
Link on promotiles are not working when "Use link label as title" is chosen

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1918] opened 2023-10-05 08:39 UTC
This is also affecting pages where we have used promotiles, e.g. the careers page, which is one of our most visited and important pages. Also tested at the top of this page: https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/global-development/desk/topicContent;d0b57050-7f22-434d-97b3-ceb8324719e1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1lJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dbc1c5e72ed61594976990d2e46c28fdadcfb12/image.png)

**Comment by fernandolucchesi** [comment] 2023-10-16 10:14
Duplicate of #1919

**Closed by fernandolucchesi** 2023-10-16 10:14 UTC
Labels: 🐛 bug
