### ISSUE TITLE
Create a separate Next application for the news archive

### ISSUE THREAD

**Issue by vnys** [equinor/energyvision#356] opened 2021-06-03 13:48 UTC
The News archive consists of almost 20.000 static pages from AEM. In order to _not_ have to rebuild the news archive every time we deploy the web application, we should extract that into it’s own application. If we build the menu so that’s it can render in the client, then we would only have to deploy the news archive application _once_ and unless there are problems it could run for years without being touched. This also makes sense from a Next perspective, since we could then identify the most popular archive pages based on page views, build and deploy those, and have the rest of the pages be built on demand. The number of built pages would then increase over time, which means the longer it runs the less pages need to be built.

**Comment by wenche** [comment] 2021-08-13 13:24
Duplicate of #374?

**Comment by nilsml** [comment] 2021-08-23 08:27
This seems indeed to be a duplicate of #374. We need to make a decision. In the meantime I close this one, and we may tack history in 374 instead.

**Closed** 2021-08-23 08:28 UTC
Labels: 🌐  Next.js (web)
