### ISSUE TITLE
As an editor I want to publish a news article at a particular time so I can schedule the date

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#237] opened 2021-04-08 11:09 UTC
## Acceptance criteria
1. CET and CEST should be automatic depending on time of year.
1. Editor should be able to publish 'now', without picking date/time.
1. Editor should be able to schedule a particular date and time to publish.
1. Date on the published article should display Date and time (eg: 7 April 2021 08:00 CEST) the article was published. 
1. If the editor edits and re publishes the article, Article should should display the original date and time and also the modified time. (eg: 23 March 2021 08:00 CET | Last modified 23 March 2021 15:50 CET)
1. Must respect time zone and daylight saving time

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by SvSven** [comment] 2021-06-09 11:10
Related issue: #287

Quote:

> - Published date should be automatically added when editor clicks publish. (real time date)
> - Date picker should only apply if editor wants to schedule the publication for a specific time and date.
> - Modify date should automatically be added once editor makes a change and re publishes. Currently it appears on the initial publish.
> - The modify date appears to show the "actual" date published when an article is first published. IE if editor sets to publish an hour ahead (ie schedule), the modify date displays the actual time one early than scheduled.

Main todo / thing missing is the actual scheduling, where the "Publication date and time" field is used to schedule the post and have that serve as publication date instead of the built-in `_createdAt` field in Sanity

**Comment by meols** [comment] 2022-01-21 14:17
@nilsml - adding a comment for the future news template work after testing a news today; editors need to be able to prepare a news article sometimes days before it is published, and to be able to add internal links we have to publish the news article. We need to ensure that we are not showing the "published to be able to add links date" but have the real "published to the world date" as the published date (and not as the modified date).

**Comment by meols** [comment] 2022-05-05 07:42
This also applies to local news @fernandolucchesi

**Comment by fernandolucchesi** [comment] 2022-06-09 12:19
Duplicate of #339

**Closed by fernandolucchesi** 2022-06-09 12:19 UTC
Labels: 📇 user story, 👨‍💻 planning
