### ISSUE TITLE
Newsroom pages aren't updated with the latest news

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2480] opened 2024-08-23 07:38 UTC
We see that neither the no or the en newsroom is updated with the latest news.

I published a news today that is visible on the homepages, but not on the newsroom pages. The English newsroom is just missing the latest news (from today), but the Norwegian newsroom is missing the one from today and two more.
<img width="1062" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45beb97bf15995d6811601f524f682b74f3ca758/image.png" alt="image.png" />

<img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d8b79f7b0af65d7826557c120e84f06dc76cf68/image.png" alt="image.png" />

**Comment by padms** [comment] 2024-08-23 07:50
@meols This is fixed. I missed updating the webhook after i18n upgrade for production.

**Comment by padms** [comment] 2024-08-23 09:34
Fixed this for all news that went missing. Will see if there are any issues with the new ones , if not we are good to close. I have updated the webhook which I missed to update after i18n.

**Comment by padms** [comment] 2024-08-29 06:32
28 th Aug news publish did not trigger webhook, so the news is not indexed. So manually trigger the indexer function.

**Comment by padms** [comment] 2024-09-11 07:08
11th sep news is not indexed. Modified the webhook to trigger on create not on update.

**Comment by padms** [comment] 2024-09-17 07:07
Confirmed that the news is indexed on 17 th sep

**Comment by padms** [comment] 2024-10-01 08:18
@meols No specific criteria to test as this is happened in prod. Two things were done to fix 

- I updated the old _lang field with the new lang field in the webhook that I missed during i18n upgrade. 
- Next, I enabled the webhook trigger on publish along with edits. This was necessary after the i18n upgrade. 

I observed the newsroom for the last two news articles published and they were indexed immediately. 
I suggest we can close this now as this is due to wrong configuration of the webhook and not a bug in the code. Please create a new one if an issue arises in future.

**Comment by meols** [comment] 2024-10-01 08:22
Thanks @padms - I agree, this can be closed.

**Closed** 2024-10-09 11:16 UTC
Labels: 🐛 bug
