### ISSUE TITLE
No top bar when landing on a 404 page.

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#769] opened 2022-01-19 14:06 UTC
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/ec611ddf-f042-4eb8-ac10-e30e384b0d80)

**Comment by SvSven** [comment] 2022-01-28 09:23
My first guess would be that it's a problem with the archived news

I tried to reproduce it by deliberately going to a page that would show a 404, but I get a different result: https://energyvision.app.radix.equinor.com/news/archive/thisslugdoesnotexist

We have an issue for that one at least: #576

Also can't reproduce it for that particular URL since it loads now: https://energyvision.app.radix.equinor.com/news/archive/20220114-key-step-advancing-offshore-wind-new-york

**Comment by padms** [comment] 2022-02-17 07:18
I am not able to reproduce this issue.

**Comment by adneforslund** [comment] 2022-02-22 07:52
Seems like nobody can reproduce this issue. Close it?

**Comment by SvSven** [comment] 2022-02-22 11:06
Probably got fixed somewhere along the line while doing something else 🤷‍♂️
We also have #500 should it ever pop up again

**Closed by SvSven** 2022-02-22 11:06 UTC
Labels: 🐛 bug, duplicate, 🕵️‍♀️ investigation, 👨‍💻 planning
