### ISSUE TITLE
Event promo - Do we always have to create an event in the template

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#795] opened 2022-01-21 08:24 UTC
Nice to have!

We have scenarios where we have to promote events throughout the year. This can be viewed here:
https://www.equinor.com/en/investors.html

For some events we have no other info other than day and title. The question is do we need to always create the event template in order to use the event promo component to promote it. It is ok to do this, however it is strange to have the button 'details' when there is no further details. If you notice on the above example, there is no read more button for certain events. Can we live with a user going to essentially a blank page? 

Could a fix be to build the page as a basic setup and publish, but the button on the promo going to the event could be hidden somehow? Toggle on the event template?

**Comment by wenche** [comment] 2022-05-11 07:12
This is a duplicate of #1007

**Closed by wenche** 2022-05-11 07:12 UTC
Labels: enhancement, ❓ question
