### ISSUE TITLE
investigate issue with unicode characters in archive

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#410] opened 2021-07-20 06:40 UTC
Some characters like apostrophes and Norwegian characters are not rendering correctly.
Example: https://energyvision.app.radix.equinor.com/news/archive/20210719-equinor-ready-to-further-develop-floating-offshore-wind-in-scotland

**Comment by padms** [comment] 2021-08-10 12:35
The issue is fixed in the Archiver Tool.

**Closed by padms** 2021-08-10 12:35 UTC
Labels: 🛠 technical
