### ISSUE TITLE
Confirm a11y for accordion in simple menu

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#801] opened 2022-01-25 07:45 UTC

**Comment by fernandolucchesi** [comment] 2022-05-13 11:25
Probably duplicate of #895

**Comment by wenche** [comment] 2022-05-18 05:56
Since it's mainly used for one menu item with multiple sub items within a list of single items, it's hard to do this in another way. I think this should be good enough since accordion is nothing but a bunch of divs and aria states and not a "real" html element. The menu as a whole should be tested with focus on a11y at some point to see if we can improve it.

**Closed by wenche** 2022-05-18 05:56 UTC
Labels: ⚙️ task
