### ISSUE TITLE
As a user I would like to navigate to specific content on a page to get straight the point (Anchor component)

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#346] opened 2021-05-27 07:16 UTC
1. [Anchor component to add to points on any given page](#715).
2. Editor can create unique and relevant naming principal.
3. Created anchor will provide a specific URL to the point on the page (eg: https://www.equinor.com/en/how-and-why.html#health-safety-security) This url is more to add to SoMe posts and for stake holders to provide links to target audiences (not something that shows in menu)
4. Editors can add an anchor point to a button/link in order to point directly to a point on another page.

For discussion: Currently the anchor link component can be utilized for in page navigation. Does this fit as part of this user story?

Currently AEM fails from a UX perspective as there are various ways to solve inpage navigation. We need a clear definition of how it should appear and behave. 

Best example:
https://www.iea.org/fuels-and-technologies/renewables (appears/hides on scroll)

**Comment by nilsml** [comment] 2021-05-28 13:05
We should discuss this story. There might be other ways of achieving the desired behaviour.

**Comment by nilsml** [comment] 2021-09-20 16:15
Duplicate of #178?

**Comment by nilsml** [comment] 2021-12-14 09:59
I can't see this anywhere in the priority list for going live or switching off AEM @nicholas-haggerty @meols cc @pradeepvenurao (It wasn|t suggested in the list from the dev team either btw)

**Comment by pradeepvenurao** [comment] 2021-12-14 10:03
If it is not in the dependent list, we should postpone this.

**Comment by nicholas-haggerty** [comment] 2021-12-15 09:36
@nilsml @meols  Its on the figjam board. Discussed several times including at the workshop. I believe is also on the PPT overview @pradeepvenurao. Does it absolutely stop us switching off AEM? No. Is it yet another missing component that the editorial will use extensively on pages, Yes. Does it majorly impact on the editorial workflow if not in place. Yes.

**Comment by nilsml** [comment] 2022-01-07 08:45
This story needs to be split into TOC and anchor link

**Comment by nilsml** [comment] 2022-01-07 08:57
Do we need support for anchor linking to static pages? That will complicate this issue and require more time for development.

**Comment by SvSven** [comment] 2022-01-07 09:00
> Do we need support for anchor linking to static pages? That will complicate this issue and require more time for development.

This will also complicate things if we make the static link selection more easy/intuitive as discussed in previous meeting.
Best would be to limit it to only dynamic pages.

Anchor links that already exist on static pages will continue to work (if linking to other static pages or to content on the same page). No guarantees that existing anchor links on static page will continue to work if the page they link to has been converted to a dynamic page in Sanity.

**Closed** 2022-01-27 13:45 UTC
Labels: 📇 user story, 🎨 UX, 🛠 technical
