### ISSUE TITLE
Provide html for backup site in Radix

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1352] opened 2022-11-04 14:27 UTC
**In order to give the user a proper message when our pods are down, we need to come up with design/markup for a backup page**

This page will be shown whenever none of our pods for equinor.com are working

**Comment by fernandolucchesi** [comment] 2022-11-07 09:19
Duplicate of #1278 https://github.com/equinor/radix-platform/issues/747, I'll close the first one since this has better description

**Comment by fernandolucchesi** [comment] 2022-11-07 09:20
@NickHaggerty1

**Comment by NickHaggerty1** [comment] 2022-11-07 10:06
@fernandolucchesi @nilsml  
No idea on this... 
Sizes? 
Requirements? 
Text? 
Image?
And I assume you guys great the html?!

**Comment by NickHaggerty1** [comment] 2022-11-07 10:06
@fernandolucchesi @nilsml  
No idea on this... 
Sizes? 
Requirements? 
Text? 
Image?
And I assume you guys great the html?!

**Comment by nilsml** [comment] 2022-11-07 10:14
There is no specific requirements other than having a nice page with a message to the user.

Something in the lines of:

"It seems like we are having some issues with our site. Our deepest apologies! Please try again in a few minutes, and hopefully we have sorted out our problems by then" 🤷🏻‍♂️

**Comment by NickHaggerty1** [comment] 2022-11-07 10:21
Could you build in Sanity like 404 page, so editor adds image and text in? If so, cant we just base it on the 404 set up and we manually add the text and image?

Or is this something different?, if so, I would need answers for the other 4 questions...

**Comment by fernandolucchesi** [comment] 2022-11-07 10:25
This is the page to be shown up when our website/infra is down. From what I can remember that was discussed during the disaster recovery meetings, there should be links to our social media communication channels, because in case of a black screen users would be able to find more information through these channels

**Comment by fernandolucchesi** [comment] 2022-11-07 10:26
> Could you build in Sanity like 404 page, so editor adds image and text in? If so, cant we just base it on the 404 set up and we manually add the text and image?
> 
> Or is this something different?, if so, I would need answers for the other 4 questions...

this shouldnt be a sanity page... is a page for when everything breaks (including sanity) 😬

**Comment by fernandolucchesi** [comment] 2022-11-07 10:29
I think it should have a "Keep calm" message approach, more of a copywriting than design to be done here IMO. On the feature request to radix I explained a bit of the context:

> Is your feature request related to a problem? Please describe.
Equinor.com is a business critical application. It might happen, as it has happened on the incident of 30th August, that the website has a downtime due to different reasons (azure, radix, our own code etc). With the current default error page "503 Service Temporarily Unavailable" our users are not informed about what is happening.

> Describe the solution you'd like
We would like to have a custom error page with support to anchor links, in order to direct our users to different communication channels (facebook/twitter/status page), where they will be able to find information about the downtime, minimising speculations.

> Describe alternatives you've considered
Fallback DNS to another address when radix server responds with error.

> Additional context
During the downtime we had, the [Equinor @ONS 2022](https://www.equinor.com/news-and-media/ons) event was happening, and journalists asked Equinor employees if we were under attack by Russian hackers 😅. We want to minimize as much as we can that such incidents affects Equinor's reputation, specially if such happens around Quarterly Results publications for investors.

**Comment by NickHaggerty1** [comment] 2022-11-07 11:57
![image.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/bf3dead1-0eee-452a-9f74-7bef4a9625cc)

**Comment by NickHaggerty1** [comment] 2022-11-07 11:59
Just to get the ball rolling here. Something like this? 
Optional to have logo? Make it look a little more correct.
Suggestion on text.
As you mentioned above in the dialogue, provide links to some....

**Comment by SvSven** [comment] 2022-11-15 09:33
Looks beautiful ♥

**Comment by SvSven** [comment] 2022-11-16 14:19
Should be said that hopefully no one ever gets to see this page - it's purely to replace the default one that would site in the (mostly unlikely) scenario that the whole site crashes.

**Comment by SvSven** [comment] 2022-11-16 14:23
Also, limitations as mentioned by the Radix team:

> Currently there are some limitations:
> 1. CSS and JS need to be implemented inside the HTML file.
> 2. Any photos or other files needs to be Base64 Encoded.

Hence why the favicon, the logo, and icons are all inline SVG (with the favicon being a URL encoded SVG - never knew that was possible)

**Comment by millianapia** [comment] 2022-11-17 09:53
> Also, limitations as mentioned by the Radix team:
> 
> > Currently there are some limitations:
> > 
> > 1. CSS and JS need to be implemented inside the HTML file.
> > 2. Any photos or other files needs to be Base64 Encoded.
> 
> Hence why the favicon, the logo, and icons are all inline SVG (with the favicon being a URL encoded SVG - never knew that was possible)

Nice workaround! looks good

**Comment by meols** [comment] 2022-11-29 08:03
@SvSven - is there anything to be tested for this one, and if so, any acceptance criteria?

**Comment by SvSven** [comment] 2022-11-29 10:11
@meols @NickHaggerty1 Nothing to be tested - just need to be confirmed that the text and the design on the screenshot I posted above is good.

**Comment by NickHaggerty1** [comment] 2022-11-29 12:12
Great Sven, good to goooooooo

**Comment by SvSven** [comment] 2022-11-29 12:13
Perfect

@fernandolucchesi how do we get this to the Radix team - you have a contact with them I believe?

**Comment by nilsml** [comment] 2022-11-30 07:57
#omnia_radix_support channel on Slack is the easiest way to reach them @SvSven

**Comment by fernandolucchesi** [comment] 2022-12-05 13:09
> Perfect
> 
> @fernandolucchesi how do we get this to the Radix team - you have a contact with them I believe?

Magnus Longva is usually my go-to guy in radix team

**Comment by SvSven** [comment] 2022-12-05 13:19
Radix team has deployed the custom error page for our cluster: https://github.com/equinor/radix-platform/issues/747#issuecomment-1334855980

**Closed by SvSven** 2022-12-05 13:19 UTC
Labels: ⚙️ task, 🍌 low hanging fruit
