### ISSUE TITLE
Quote component text colour doesn't change to white in the name field on the dark blue background

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1271] opened 2022-09-08 07:24 UTC
![Screenshot 2022-09-08 at 09.22.00.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/71165a60-cf3e-4de9-8525-1f0d3f3b8801)

**Comment by NickHaggerty1** [comment] 2022-09-08 07:32
Example can be found on the front page of .com on 8/09/22

**Comment by SvSven** [comment] 2022-09-08 07:51
Should be a quick fix. The author text is indeed not being inverted with the dark background, but this only happens if no author title is added. It should work if there is both an author name and title.

For whoever works on this, the problem is here: https://github.com/equinor/energyvision/blob/main/web/components/src/Quote/Author.tsx#L46

The text there should be wrapped in an element that contains this CSS code:

```css
  .inverted-background & {
    color: var(--inverted-text);
  }
```

**Comment by NickHaggerty1** [comment] 2022-09-08 09:20
Yes, it was a slightly weird one because as you say, it worked fine when Name and Title were in place.

**Comment by SvSven** [comment] 2022-09-21 12:15
@NickHaggerty1 should be fixed now - you can test it on the development dataset

**Closed** 2022-09-27 11:06 UTC
Labels: 🐛 bug, 🍌 low hanging fruit
