### ISSUE TITLE
Multiple promotion cards are different height

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2044] opened 2024-01-09 09:56 UTC
<img width="1053" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--074068e970c4c7b26e64e20375d12381b413a0ca/Screenshot%202024-01-09%20at%2010.55.42.png" alt="Screenshot 2024-01-09 at 10.55.42.png" />

**Comment by BorghildSelle** [comment] 2024-02-02 13:32
Could not reproduce, only found 1 place on Malins test page on Malins computer:)
Closing this. If it should happen again, a new issue will be created.

**Closed by BorghildSelle** 2024-02-02 13:32 UTC
Labels: 🐛 bug
